name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
          check-latest: true

      - name: Set up goproxy
        run: |
          go env -w GO111MODULE=on
          go env -w GOPROXY=https://goproxy.cn,direct

      - name: set env
        run: echo IMAGE_TAG=$(git describe --tags) >> $GITHUB_ENV

      - name: static build
        run: make build-static

      - name: docker build
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: docker push
        run: |
          docker login --username=${{ secrets.DOCKER_ALIYUN_USERNAME }} --password=${{ secrets.DOCKER_ALIYUN_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: slack message
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.SLACK_WEBHOOK_API }}
          headers: '{"Content-Type": "application/json"}'
          body: '{"text": "Image Pushed: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"}'
